In [1]:
import src.tablas as tablas

tablas.transmision()

,COD_TRANSMISION,CEDULA_TRANSMITIO,JUNTA_TRANSMITIDA,TOTAL_SUFRAGANTES,P1_SI,P1_NO,P1_BLANCOS,P1_NULOS,P1_VALIDA,P2_SI,...,P11_NO,P11_BLANCOS,P11_NULOS,P11_VALIDA,SUBIO_TIPO_ACTA_1,SUBIO_TIPO_ACTA_2,DELEGADO_ENVIO_INFORMACION,FECHA_HORA,COD_VERIFICADOR,VERIFICADA
0,383,DIG12,12882,54,34,11,3,6,1,31,...,20,5,6,1,0,1,0,Apr 21 2024 11:02PM,0,0
1,384,DIG20,9158,58,39,9,6,4,1,40,...,12,4,2,1,0,1,0,Apr 21 2024 11:15PM,VER2,1
2,385,DIG20,35534,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,Apr 21 2024 11:17PM,0,0
3,386,DIG18,4333,118,22,82,3,11,1,15,...,89,6,11,1,0,1,0,Apr 21 2024 11:19PM,VER7,1
4,387,DIG19,9159,54,40,8,2,4,1,34,...,15,9,2,1,0,1,0,Apr 21 2024 11:20PM,VER1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10387,11737,DIG45,22215,313,187,59,15,52,1,172,...,80,20,55,1,0,1,0,Apr 22 2024 4:03PM,0,0
10388,11738,DIG54,22216,306,196,64,14,32,1,167,...,94,32,28,1,0,1,0,Apr 22 2024 4:03PM,0,0
10389,11739,DIG22,22208,305,189,81,22,12,1,170,...,101,35,12,0,0,1,0,Apr 22 2024 4:03PM,0,0
10390,11740,DIG24,22207,322,192,78,17,35,1,168,...,106,32,30,1,0,1,0,Apr 22 2024 4:03PM,0,0
10391,11741,DIG50,22220,301,170,75,21,35,1,147,...,88,41,32,1,0,1,0,Apr 22 2024 4:03PM,0,0

In [4]:
import pandas as pd

# Crear el DataFrame con los datos proporcionados
data = {
    'ERROR_ESTANDAR_NO_SN': [0.03219612209547486, 0.0303425282316338, 0.02396783298943947, 0.020547996969444506, 0.01982472110737813, 0.014894480467959327, 0.01304864725308187, 0.010848739886147575, 0.009426997243103533, 0.008256657263014071, 0.007336538665746115, 0.006339194705255134, 0.004799667799554347, 0.0040976987553159065, 0.0036489725987130417, 0.0034732085977705893, 0.0030713989344870207, 0.002921310252644028, 0.0027293834329978396, 0.0025253784645046175, 0.0024793442592982505, 0.002298719793873885, 0.002218436170116455, 0.0021824362155769554, 0.0020814984696968485, 0.0019474412256900654, 0.001843856911279603, 0.0017693219304723694, 0.0017281031323488235, 0.0016577530157739046, 0.0015984544805230047, 0.0015564935272319705, 0.0015228845854552775, 0.0014684341922998033, 0.0014266243018192272, 0.0013968004995609299, 0.0013697140161806774, 0.0013467870505185632, 0.0013053452759881393, 0.0012877402832537532, 0.0012515041314292642, 0.0012274196658187395, 0.001206726221997978, 0.0011606640323809092, 0.001149400457459305, 0.0011395782142958918, 0.0011338060628697298, 0.0011287341099821514, 0.001120878163229125, 0.001120145879530906, 0.0010916338730428173, 0.0010860987698655313, 0.0010804323724327876, 0.0010744838579379756, 0.001068767615196811, 0.0010614011028614117, 0.0010457706929024482, 0.0010395656466682928, 0.0010326286879698934, 0.0010250726693304998, 0.0010180338040265617, 0.0010153968130705209, 0.0010106531103100153, 0.001007230473233131, 0.0010003368226282248, 0.000996028426476841, 0.0009900624714503914, 0.000986136030703049, 0.000981516874170061, 0.0009633994206569877, 0.0009511324702101673, 0.0009468908572488021, 0.0009415012143968195, 0.0009305090578533784, 0.000929051144564564, 0.0009261307227145062, 0.0009206768834654884, 0.0009165153474948303, 0.0009136996107457366, 0.0008954892406395775, 0.0008880802271283496, 0.0008874179806353724, 0.0008859905574812249, 0.0008747992994399963, 0.0008707941046877874, 0.0008613254633951463, 0.0008595566052033584, 0.0008558107962983527, 0.0008496886998910665, 0.0008456307189280298, 0.0008400442837346458, 0.0008359919989019988, 0.0008286354845441979, 0.0008256478234598793, 0.0008230856868876041, 0.0008218699218916309, 0.0008203792689270856, 0.0008189966795365375, 0.0008166395027212211, 0.0008160322628797071]
}
df = pd.DataFrame(data)
df['ERROR_ESTANDAR_NO_SN'] = df['ERROR_ESTANDAR_NO_SN'].astype(float)

# Crear una funciÃ³n para determinar si la diferencia es menor a 0.001
def diff_less_than_threshold(value, threshold=0.001):
    index = df.index[df['ERROR_ESTANDAR_NO_SN'] == value][0]  # Obtener el Ã­ndice de 'value'
    return all(abs(value - df['ERROR_ESTANDAR_NO_SN'].iloc[i]) < threshold for i in range(index + 1, len(df)))

# Aplicar la funciÃ³n a cada fila y crear la nueva columna
df['NUEVA_COLUMNA'] = df['ERROR_ESTANDAR_NO_SN'].apply(diff_less_than_threshold)

# Convertir los valores booleanos en 1 y 0
df['NUEVA_COLUMNA'] = df['NUEVA_COLUMNA'].astype(int)

print(df)

   ERROR_ESTANDAR_NO_SN  NUEVA_COLUMNA
0              0.032196              0
1              0.030343              0
2              0.023968              0
3              0.020548              0
4              0.019825              0
5              0.014894              0
6              0.013049              0
7              0.010849              0
8              0.009427              0
9              0.008257              1